---
title: Estimating Quantile Regressions with Multiple Fixed Effects through Method of Moments \tnoteref{t1}
author:
  - name: Fernando Rios-Avila
    email: friosavi@levy.org
    affiliations: 
        - id: levy
          name: Levy Economics Institute of Bard College          
    attributes:
        corresponding: true
  - name: Leonardo Siles
    email: leonardo.siles@ucb.edu.bo
    affiliations:
        - name: Universidad Católica Boliviana
          id: ucb
  - name: Gustavo Canavire-Bacarreza
    email: gcanavire@worldbank.org
    affiliations:
        - id: wb
          name: World Bank                 
abstract: |
  This paper proposes a new method to estimate quantile regressions with multiple fixed effects. The method, which expands on the strategy proposed by @mss2019, allows for the inclusion of multiple fixed effects and provides various alternatives for the estimation of standard errors. We provide Monte Carlo simulations to show the finite sample properties of the proposed method in the presence of two sets of fixed effects. Finally, we apply the proposed method to estimate the determinants of the surplus of government as a share of GDP, allowing for both time and country fixed effects.
  
keywords: 
  - Fixed effects
  - Linear heteroskedasticity
  - Location-scale model
  - Quantile regression

date: last-modified
bibliography: bibliography.bib
format:
  elsevier-pdf:
    keep-tex: true
    journal:
      formatting: review
      model: 1p
      cite-style: authoryear
      number-depth: 2
include-in-header: 
      text: |
        \tnotetext[t1]{The opinions expressed in this paper are those of the authors and do not necessarily reflect the views of the World Bank, its Board of Directors, or the countries it represents.}        
---


<!--
How to Render this?
Lik this:
quarto render article.qmd --to elsevier-pdf

-->

# Introduction

Quantile regression (QR), introduced by @koenkerbasset1978, is an estimation strategy used for modeling the relationships between explanatory variables X and the conditional quantiles of the dependent variable $Q_y (\tau|x)$. Using QR one can obtain richer characterizations of the relationships between dependent and independent variables, by exploring how the variables relate along the entire conditional distribution.

A relatively recent development in the literature has focused on extending quantile regressions analysis to include individual fixed effects in the framework of panel data. However, as described in @neymanscott1948, and @lancaster2000,  when individual fixed effects are included in quantile regression analysis an incidental parameter problem is generated. While many strategies have been proposed for estimating this type of model (see @galvao2017quantile for a brief review), neither has become standard because of their restrictive assumptions in regard to the inclusion of individual and multiple fixed effects, the computational complexity, and implementation.

More recently, @mss2019 (MSS hereafter) proposed a methodology based on a conditional location-scale model, similar to the one described in @he1997 and @zhao2000, for the estimation of quantile regressions models for panel data via a method of moments. This method allows individual fixed effects to have heterogeneous effects on the entire conditional distribution of the outcome, rather than constraining their effect to be a location shift only, as in @canay2011, @koenker2004, and @lamarche2010.

In principle, under the assumption that data-generating process behind the data is based on a multiplicative heteroskedastic process that is linear in parameters [@mss2019, @he1997, @zhao2000, @cameron2005], the effect of a variable $X$ on the $q_{th}$ quantile can be derived as the combination of a location effect, and scale effect moderated by the quantile of an underlying i.i.d. error. For statistical inference, MSS derives the asymptotic distribution of the estimator, suggesting the use of bootstrap standard errors, as well.

This methodology is not meant to substitute for the use of standard quantile regression analysis. That said, given the assumptions required for the identification of the model, it provides a simple and fast alternative for the estimation of quantile regression models with individual fixed effects.

In this framework, our paper expands on @mss2019 in two ways. First, making use of the properties of generalized method of moments (GMM) estimators, we derive various alternatives for the estimation of standard errors based on the empirical influence functions of the estimators. Even if the model is correctly specified, robust standard errors perform better than GLS standard errors due small violations of the model assumptions due to sampling variability. Furthermore, clustered standard errors may help to further account for typically unobserved correlations across observations. Second, we reconsider the application of Frisch-Waugh-Lovell (FWL) theorem [@frishwaugh1933 and @lovell1963] to extend the MSS estimator and allow for the inclusion of multiple fixed effects. This extension may be useful for empirical analysis, as it is common to control for multiple fixed effects such as individual and time fixed effects. 

The rest of the paper is structured as follows: section 2 presents the basic setup of the location-scale model described in @he1997 and @zhao2000, tying the relationship between the standard quantile regression model and the location-scale model. It also revisits the methodology of MSS, proposing alternative estimators for the standard errors based on the properties of GMM estimators and the empirical influence functions. It also shows that the FWL theorem can be used to control for multiple fixed effects. Section 3 presents the results of a small simulation study and section 4 illustrates the application of the proposed methods with one empirical example. Section 5 concludes.

# Methodology {#sec-method}

## Quantile Regression: Location-Scale model {#sec-betas}

Quantile regressions are used to identify relationships between the explanatory variables $X$ and the conditional quantiles of the dependent variable $Q_y(\tau|X)$. This relationship is commonly assumed to follow a linear functional form:

$$Q_y(\tau|X) =X\beta(\tau)
$$ {#eq-eq1}

This allows for a linear effect of $X$ on $Y$, but that could vary across values of $\tau$. 

An alternative formulation of quantile regressions is the location-scale model. This approach assumes that the conditional quantile of $Y$ given $X$ and $\tau$ can be expressed as a combination of two models: the location model, which describes the central tendency of the conditional distribution; and the scale model, which describes deviations from the central tendency:

$$Q_y(\tau|X) =X\beta+X\gamma(\tau)
$$ {#eq-eq2}

Here, the location parameters $\beta$ are typically identified using a linear regression model (as in @mss2019) or a median regression (as in @he1997 and @zhao2000) and the scale parameters $\gamma(\tau)$ can be estimated using standard approaches.

Both the standard quantile regression (@eq-eq1) and the location-scale specification (@eq-eq2) can be estimated as the solution to a weighted minimization problem:

$$\hat{\beta}(\tau) = \underset{\beta}{\operatorname{argmin}}
\left( \sum_{i\in y_i\geq x_i'\beta} \tau (y_i - x_i'\beta) - \sum_{i\in y_i<x_i'\beta} (1-\tau)(y_i - x_i'\beta) \right)
$$ {#eq-eq3}

One characteristic of this estimator is that the $\beta(\tau)$ coefficients are identified locally and thus the estimated quantile coefficients will exhibit considerable variation when analyzed across $\tau$. It is also implicit that if one requires an analysis of the entire distribution, it would be necessary to estimate the model for each quantile.[^1]

[^1]: There are other estimators that provide smoother estimates for the quantile regression coefficients using a kernel local weighted approach [@kaplan2017], as well as identifying the full set of quantile coefficients while simultaneously assuming some parametric functional forms [@frumentobotai2016].

One insightful extension to the location-scale parameterizations suggested by @he1997, @zhao2000, @cameron2005, and @mss2019 is to assume that the data-generating process (DGP) can be written as a linear model with a multiplicative heteroskedastic process that is linear in parameters.[^2]

[^2]: @mss2019 also discuss a model where heteroskedasticity can be an arbitrary nonlinear function $\sigma(x_i'\gamma)$, but develop the estimator for the linear case, i.e., when $\sigma()$ is the identity function.

$$\begin{aligned}
y_i &=x_i'\beta+\nu_i \\
\nu_i &=\varepsilon_i \times x_i'\gamma 
\end{aligned}
$$ {#eq-eq4}

Under the assumption that $\varepsilon$ is an i.i.d. unobserved random variable that is independent of $X$, the conditional quantile of $Y$ given $X$ and $\tau$ can be written as

$$Q_y(\tau|X) =X\beta+Q_\varepsilon(\tau) \times X\gamma 
$$ {#eq-eq5}

In this setup, the traditional quantile coefficients are identified as the location model coefficients plus the scale model coefficients moderated by the $\tau_{th}$ unconditional quantile of the standardized error $\varepsilon$. For simplicity we will use $q_\tau$ to denote $Q_\varepsilon(\tau)$ in the rest of the paper.

$$\beta(\tau) = \beta + q_\tau \times \gamma 
$$ {#eq-eq6}

While this specification imposes a strong assumption on the DGP, it has two advantages over the standard quantile regression model. First, because the location-scale model can be identified globally, with only a single parameter ($q_\tau$) requiring local estimation, this estimation approach will be more efficient than the standard quantile regression model (@zhao2000). Second, under the assumption that $X\gamma$ is strictly positive, the model will produce quantile coefficients that do not cross (@he1997). 

Following MSS, the quantile regression model defined by @eq-eq5 can be estimated using a generalized method of moments approach. And while it is possible to identify all coefficients ($\beta,\gamma, q_\tau$) simultaneously, we describe and use the implementation approach advocated by MSS, which identifies each set of coefficients separately.

First, the location model can be estimated using a standard linear regression model, where the dependent variable is the outcome $Y$ and the independent variables are the explanatory variables $X$ (including a constant) with an error $u$, which is by definition heteroskedastic. In this case, the location-model coefficients are identified under the following condition:

$$\begin{aligned}
      y_i &=x_i'\beta+\nu_i \\
      E\big[ x_i \nu_i\big] &=0
      \end{aligned}
$$ {#eq-eq7}

Second, after the location model is estimated, the scale coefficients can be identified by modeling heteroskedasticity as a linear function of characteristics $X$. For this we use the absolute value of the errors from the location model $u$ as dependent variable, which allows us to estimate the conditional standard deviation (rather than conditional variance) of the errors. In this case, the coefficients are identified under the following condition:

$$\begin{aligned}
  |\nu_i| &=x_i'\gamma+\omega_i \\
   E\big[ x_i (|\nu_i| -x_i'\gamma ) \big] &=0
  \end{aligned}
$$ {#eq-eq8}

It should be noticed that the estimation of the standard errors (next section) requires that the Scale component prediction $x_i'\gamma$ is strictly positive, because it represents the conditional standard deviation of the error $\nu_i$. Because this component is identified using a linear model, some values for $x_i'\gamma$ may be negative, which will affect the estimation of the standard errors, as shown in the simulation study.

Third, given the location and scale coefficients, the $\tau_{th}$ quantile of the error $\varepsilon$ can be estimated using the following condition:

$$\begin{aligned}
  E\left[  \mathbb{1}\left(x_i' (\beta +   \gamma q_\tau) \geq y_i \right) - \tau \right] &=0  \\
  E\left[  \mathbb{1}\left(   q_\tau \geq \frac{y_i-x_i'\beta}{x_i'\gamma} \right) - \tau \right] &=0  \\
  \end{aligned}
$$ {#eq-eq9}

where one identifies the quantile of the error $\varepsilon$ using standardized errors $\frac{y_i-x_i'\beta}{x_i'\gamma}$ or by finding the values that identify the overall quantile coefficients $\beta(\tau)=\beta + \gamma q_\tau$. Afterwards, the conditional quantile coefficients are simply defined as the combination of the location and scale coefficients.



## Standard Errors: GLS, Robust, Clustered {#sec-se}

As discussed in the previous section, the estimation of quantile regression coefficients using the location-scale model with heteroskedastic linear errors can be estimated using a the following set of moments, which fits within the GMM framework:

$$\begin{aligned}
  E[x_i \nu_i  ] &= E[h_{1,i}]=0 \\
  E[x_i  (|\nu_i|-x_i \gamma) ] &=E[h_{2,i}]=0 \\
  E\left[  \mathbb{1}\left(   q_\tau\geq \frac{y_i-x_i'\beta}{x_i'\gamma} \right) - \tau \right]  &=E[h_{3,i}]=0 
  \end{aligned}
$${#eq-eq10}

Under the conditions described in @newey_chapter_1994 (see section 7), @cameron2005 (see chapter 6.3.9), or as shown in @mss2019, the location, scale, and residual quantile coefficients are asymptotically normal.[^3]

[^3]: @zhao2000 also shows that the quantile coefficients for the location-scale model follow a normal distribution, but uses the assumption that the location model is derived using a least absolute deviation approach (median regression).

Call $\theta=[ \beta' \ \ \gamma' \ \ q_\tau ]'$ the set of coefficients that are identified by the moment conditions in @eq-eq10, a just identified model, and the function $h_i$ is a vector function that stacks all the moments described in @eq-eq10 at the individual level. Then $\hat\theta$ follows a normal distribution with mean $\theta$ and variance-covariance matrix $V(\theta)$ that is estimated as

$$
\hat{V}(\hat\theta)=\frac{1}{N} 
\bar G(\hat\theta)^{-1} 
\left( \frac{1}{N} \sum_{i=1}^N h_i h_i'  \Big|_{\theta=\hat\theta} \right) 
\bar G(\hat\theta)^{-1} 
$$

which is equivalent to the Eicker-White heteroskedasticity-consistent estimator for least-squares estimators.

Here, the inner product is the moment covariance matrix and $\bar{G}(\theta)$ is the Jacobian matrix of the moment equations evaluated at $\hat\theta$.

$$\bar{G}(\theta) =-\frac{1}{N} \sum_{i=1} \frac{\partial h_i}{\partial \theta'} \Big|_{\theta=\hat\theta}$$

In this framework, the quantile regression coefficients, a combination of the location-scale-quantile estimates, will follow a normal distribution with mean $\beta(\tau) = \beta+\gamma q_\tau$ and variance-covariance matrix equal to

$$\hat{V}(\beta(\tau)) = \Xi \hat{V}(\hat\theta) \Xi'
$$

where $\Xi$ is a $k \times (2k+1)$ matrix defined as

$$\Xi = [ I(k), \hat q_\tau \times I(k), \hat \gamma ]
$${#eq-eqqtile}

with $I(k)$ being an identity matrix of dimension $k$ (number of explanatory variables in $X$ including the constant).

While it is possible to estimate the variance-covariance matrix using simultaneous model estimation for a just identified model, it is more efficient to estimate each set of coefficients separately. Afterward, the variance-covariance matrix can be estimated using the empirical influence functions of the estimators (see @jann_2020 for an overview of the application and @hampel2005 for an in-depth review).

Specifically, given an arbitrary vector of empirical influence functions $\lambda_i(\theta)$, the variance-covariance matrix can be estimated as

$$\hat{V}(\theta) = \frac{1}{N^2} \sum_{i=1}^N \lambda_i(\theta) \lambda_i(\theta)'
$$ {#eq-eqvcv}

where the influence functions are defined as:

$$\lambda_i(\theta) = \bar G(\theta)^{-1} h_i(\theta)$$

For the specific case of quantile regressions via moments, the influence functions for the location, scale, and quantile coefficients are[^4]

[^4]: The derivation of the influence functions can be found in the appendix.

$$\begin{aligned}
\lambda_i(\theta)&=
  \begin{bmatrix}
  \lambda_{i}(\beta) \\
  \lambda_{i}(\gamma) \\
  \lambda_{i}(q_\tau) 
  \end{bmatrix} \\
\lambda_{i}(\beta)&=N (X'X)^{-1}  x_i ( x_i'\gamma) \times \varepsilon_i \\
\lambda_{i}(\gamma)&= N(X'X)^{-1} x_i ( x_i' \gamma ) \times (\tilde \varepsilon_i -1\big)\\
\lambda_{i}(q_\tau)&=\frac{\tau-\mathbb{1}\big( q_\tau  \geq \varepsilon_i  \big) }{f_{\varepsilon}(q_\tau)}
- \frac{ x_i'\gamma \times \varepsilon_i }{\bar x_i'\gamma} 
-  q_\tau \frac{  x_i' \gamma  \times (\tilde \varepsilon_i -1\big)}{\bar x_i'\gamma}
\end{aligned}
$$ {#eq-ifs}

The different types of standard errors estimation thus depend on the assumptions imposed for the estimation of $V(\theta)$.

### Robust Standard Errors

The first and most natural standard error estimator is given by equation @eq-eqvcv. This is equivalent to the Eicker-White heteroskedasticity-consistent estimator for least-squares estimators. Considering the location-scale model, the variance-covariance matrix for the quantile coefficients can be estimated as

$$\hat{V}_{robust}
  \begin{pmatrix}
  \hat\beta \\
  \hat\gamma \\
  \hat q_\tau
  \end{pmatrix}
 = \frac{1}{N^2} 
 \begin{pmatrix}
 \sum \lambda_i(\beta) \lambda_i(\beta)' & \sum \lambda_i(\beta) \lambda_i(\gamma)' & \sum \lambda_i(\beta) \lambda_i(q_\tau)' \\
 \sum \lambda_i(\gamma) \lambda_i(\beta)' & \sum \lambda_i(\gamma) \lambda_i(\gamma)' & \sum \lambda_i(\gamma) \lambda_i(q_\tau)' \\
 \sum \lambda_i(q_\tau) \lambda_i(\beta)' & \sum \lambda_i(q_\tau)\lambda_i(\gamma)' & \sum \lambda_i(q_\tau) \lambda_i(q_\tau)' 
  \end{pmatrix}
$$

This estimator of standard errors may prove useful for two reasons. First, this estimator would be robust to misspecification of the scale model assumptions, and thus it could be used as an informal test for the validity of the model assumptions when compared to the GLS-standard error (@sec-gls). Second, as shown in the simulation study, this estimator performs better than GLS-standard errors even if the model is correctly specified, because of problemes caused when $x\hat\gamma$ is not strictly positive.

### Clustered Standard Errors

Because one of the typical applications of quantile regressions is the analysis of panel data, allowing for clustered standard errors at the individual level is important. If the unobserved error $\varepsilon$ is correlated within clusters, generalized least squares (GLS) standard errors could be severely biased. The standard recommendation has been to report block-bootstrap standard errors, clustered at the individual level.

Because we have access to the influence functions, it is straightforward to estimate one-way clustered standard errors.

Let $N_G$ be the total number of clusters $g$, where $g=1\dots N_G$. The clustered variance covariance matrix is given by[^5]

[^5]: It should be noted that one could just as well apply the insights of @cameron_robust_2011, allowing for multiway clustering.

$$\hat{V}_{clustered}
  \begin{pmatrix}
  \hat\beta \\
  \hat\gamma \\
  \hat q_\tau
  \end{pmatrix}
 = \frac{1}{N^2} 
 \begin{pmatrix}
 \sum_{g=1}^{N_G} S\lambda_i(\theta) S\lambda_i(\theta)'
  \end{pmatrix}
$$

where $S\lambda_i(\theta)$ is the sum of the influence functions over all observations within a given cluster $g$.

$$S\lambda_i(\theta) = \sum_{i\in g} \lambda_i(\theta)
$$

### GLS Standard Errors {#sec-gls}

The standard errors proposed by MSS can be understood as an application of GLS, which will be valid as long as the model for heteroskedasticity is correctly specified.[^6] To estimate the GLS standard errors, we make use of the following property:

[^6]: As discussed in most econometric textbooks, for example @cameron2005, one approach to correct for heteroskedasticity, when the heteroskedasticity functional form is known or can be estimated, is to use weighted least squares. While feasible this approach would defeat the purpose of identifying quantile effects exploiting the heteroskedasticity of the model.

Consider the influence functions and robust variance-covariance matrix for the location coefficients:

$$\begin{aligned}
\hat V(\hat \beta) &= \frac{1}{N} \sum_i^N \lambda_{i}(\beta) \lambda_{i}(\beta)' \\
&= \frac{1}{N}  (X'X)^{-1}  \sum_i^N x_i x_i' ( x_i'\gamma \times \varepsilon_i)^2 (X'X)^{-1} \\
\end{aligned}
$$

Under the assumption that the model for heteroskedasticity is correctly specified, we can apply the law of iterated expectations and rewrite the variance-covariance matrix as

$$\begin{aligned}
\hat V(\hat \beta) &= \frac{1}{N} \sum_i^N \lambda_{i}(\beta) \lambda_{i}(\beta)' \\
&= E(\varepsilon_i^2) \frac{1}{N}  (X'X)^{-1}  \sum_i^N x_i x_i' ( x_i'\gamma)^2 (X'X)^{-1} \\
&= \sigma^2_{\varepsilon} \frac{1}{N}  (X'X)^{-1}  \hat\Omega_{\beta\beta} (X'X)^{-1}  
\end{aligned}
$$

This standard error estimator is an application of GLS that accounts for the heteroskedasticity the model uses to identify the quantile coefficients. We can apply the same principle to find the GLS standard errors for the system of location-scale and quantile coefficients. To do this, we define the following modified influence functions:

$$\begin{aligned}
\tilde \lambda_{1,i}&=\tilde \lambda_{2,i}=N (X'X)^{-1}  x_i ( x_i'\gamma) \\  
\tilde \lambda_{3,i}&=x_i' \gamma  \\
 \psi_{i,1} &= \varepsilon_i \\
 \psi_{i,2} &= \tilde \varepsilon_i -1 \\
 \psi_{i,3} &= \frac{1}{ x_i' \gamma }\frac{\tau-\mathbb{1}\big( q_\tau  \geq \varepsilon_i  \big) }{ f_{\varepsilon}(q_\tau)} - \frac{\varepsilon_i }{\bar x_i'\gamma} 
-  q_\tau \frac{(\tilde \varepsilon_i -1\big)}{\bar x_i'\gamma}
\end{aligned}
$$

Then, the GLS standard errors for the location-scale and quantile coefficients can be estimated as

$$\hat{V}_{gls}
  \begin{pmatrix}
  \hat\beta \\
  \hat\gamma \\
  \hat q_\tau
  \end{pmatrix}
 = \frac{1}{N^2} 
 \begin{pmatrix}
 \hat\sigma_{11} \hat\Omega_{11} & \hat\sigma_{12} \hat\Omega_{12} & \hat\sigma_{13} \hat\Omega_{13} \\
 \hat\sigma_{12} \hat\Omega_{12} & \hat\sigma_{22} \hat\Omega_{22} & \hat\sigma_{23} \hat\Omega_{23} \\
 \hat\sigma_{13} \hat\Omega_{13} & \hat\sigma_{23} \hat\Omega_{23} & \hat\sigma_{33} \hat\Omega_{33}
  \end{pmatrix}
$$

where

$$\begin{aligned}
\hat\Omega_{jk} &= \frac{1}{N} \sum_{i=1}^N \tilde \lambda_{i,j}(\theta) \tilde \lambda_{i,k}(\theta)' \\
\hat\sigma_{jk} &= \frac{1}{N} \sum_{i=1}^N \psi_{i,j} \psi_{i,k}
\end{aligned}
$$

This estimator of standard errors is equivalent to the one derived by MSS using Theorem 3. Empirically, the simulation study shows that this estimator may severily over estimate the standard errors, even if the model is correctly specified. This happens because the sample estimates of the scale model coefficients may be negative or close to zero.

## Multiple Fixed Effects: Expanding on @mss2019

Using the setup described in the previous section, MSS proposes an extension to the model proposed by @he1997 that enables the estimation of quantile regression models with panel data, allowing for the inclusion of individual fixed effects. However, the methodology can also be generalized to allow for the inclusion of multiple fixed effects. This type of analysis can be useful when considering data such as employer-employee linked data [@abowed2006] or teacher-student linked data [@harrissass2011]. Or, in the most common case, allowing to control for both individual and time fixed effects.

We return to the original model and now assume there are sets of unobserved heterogeneity that are constant across observations, if they belong to common groups. Without loss of generality, we can assume that the data-generating process is as follows:

$$\begin{aligned}
  y_{i} &= x_{i}' \beta + \delta_{g1} + \delta_{g2} + \nu_i \\
  \nu_i &= \varepsilon_i \times (x_{i}' \gamma + \zeta_{g1} + \zeta_{g2})   
  \end{aligned}
$$

where we assume $x_{i}$ vary across groups $g_1$ and $g_2$ (and thus are not collinear) and that $\delta's$ and $\zeta's$ are the location and scale effects associated with the groups fixed effects.[^7]

[^7]: We could just as well consider multiple sets of fixed effects.

If the dimension of groups $g_k$ is low, this model could be estimated using a dummy inclusion approach following @sec-betas, and the standard errors obtained as discussed in @sec-se. However, if the dimensionality of $g_k$ is high, the dummy inclusion approach may not be computationally feasible. A more feasible approach is to apply the FWL theorem and partial out the impact of the group fixed effects on the control variables $x_{i}$, and the outcome of interest $y_{i}$, and using a similar approach for the identification of $\sigma(x)$. In the case of unbalanced setups with multiple groups, the estimation involves iterative processes for which various approaches have been suggested and implemented (see for example, @correia_feasible_nodate, @gaure2013, @rios2015, among others).

When applying the partialing-out approach, some modifications to the approach described in @sec-betas are needed.

First, for all dependent and independent variables in the model ($w=y,x$), we partial out the group fixed effects and obtain the centered-residualized variables:

$$\begin{aligned}
w_{i} &= \delta_{g1}^w + \delta_{g2}^w + u_{i}^w \\
w_{i}^{rc} &= E(w_{i}) + \hat{u}_{i}^w
\end{aligned}
$$

Afterward, we estimate the location model using the centered-residualized variables:[^8]

[^8]: Using centered-residualized variables allows us to include a constant in the model specification, which simplifies the derivation of the influence functions. However, as with other fixed effects models, the constant is not identified and thus should not be interpreted.

$$y_{i}^{rc} = x_{i}^{rc'} \beta + \nu_{i}
$$

Because $|\hat \nu_i|$ is the dependent variable for the scale model, we apply the partialing out and recentering to this expression ($|\hat \nu_i|^{rc}$), and use that to estimate the following model:

$$|\hat\nu_{i}|^{rc} = x_{i}^{rc'} \gamma + \omega_{i}$$

Finally, the standardized residuals $\varepsilon_i$ can be obtained as follows:

$$\hat{\varepsilon}_{i} = \frac{\nu_{i}}{|\hat\nu_{i}|- \hat \omega_{i}}$$

where $|\hat\nu_{i}|- \hat \omega_{i}$ is the prediction for the conditional standard deviation $\sigma(x_i)=x_{i}' \gamma + \zeta_{g1} + \zeta_{g2}$

The $\tau_{th}$ quantile of the error $\varepsilon$ can be estimated as usual and the variance-covariance matrices obtained in the same way as before (see @sec-se) by using $x_{i}^{rc}$ instead of $x_{i}$ when estimating the influence functions for all estimated coefficients.

# Simulation Evidence

To show the performance of the extended strategy, we implement a small simulation study. We consider a simple model with a single explanatory variable $x$. In contrast with MSS, we consider a two-way fixed effect structure that is more general than the panel structure. For this exercise, we consider the following data-generating process:

$$y_i = \alpha_{1i} + \alpha_{2i} + x_i + (1+x_i + \alpha_{1i} + \alpha_{2i} ) \varepsilon_i
$$

where $\alpha_{1i}\sim \chi^2(1)$, $\alpha_{2i} \sim \chi^2(1)$, and $x_i = 0.5 * (\chi_i +0.5(\alpha_{1i}+\alpha_{2i}))$, with $\chi_i \sim \chi^2(1)$. We only consider the case when the error term $\varepsilon_i$ is assumed to follow a centered $\chi^2$ distribution.[^99] We assume that there are 50 mutually exclusive groups for each set of fixed effects. Observations are assigned to each subgroup randomly using a uniform distribution between 1 and 50. We consider sample sizes of 500, 1000, 2000, and 4000 observations, which implies an average of 10, 20, 40, and 80 observations per group. The model is estimated using the location-scale model with heteroskedastic linear errors and we report the coefficients for the 25th and 75th quantiles. We run this excercise 5000 times. @tbl-sim1 reports the bias, simulated standard error, and mean squared error. We also report the results obtained using an adaptation bias-corrected estimator based on the split-panel jackknife estimator proposed by @dhaene2015.[^9] These results are labeled JKC.

[^99]: Specifically we assume $\varepsilon=\frac{r_i}{5}-1$, where $r_i$ follows a chi-squared distribution such that $r_i \sim \chi^2(5)$. Simulations under the assumption of normal errors are available upon request.


[^9]: For the implementation, we first estimate the model using the full sample, then randomly assign each observation into one of two groups, and finally reestimate the quantile coefficients for each group. The bias-corrected estimator is then obtained as $\hat\beta(\tau)_{jkc}=2*\hat\beta(\tau)_{full}-0.5*\big(\hat\beta(\tau)_{s1}+\hat\beta(\tau)_{s2}\big)$.

Similar to the findings in MSS, we find that while the estimator presents a substantial bias when the sample is small ($N=500$), this bias shrinks as the sample size increases. As MSS describes, the bias seems to be proportional to the sample size, or more precisely to $N/N_{g1}$ and $N/N_{g2}$, where $N_{g1}$ and $N_{g2}$ are the average number of observations per group. Interestingly, the bias-corrected estimator presents an almost 0 bias for the 25th percentile, even when the samples are small (about 10 observations per subgroup). In contrast, when considering the 75th percentile, the simple estimator shows smaller bias than the Jacknife estimator.[^88: This is also consistent with simulations with a single fixed effect] In either case, despite the bias reduction obtained using the JKC estimator, the standard errors  are larger than without correction. For the 25th quantile, the reduction in bias is large enough to produce a smaller Mean Squared Error (MSE) than the simple estimator. This is similar to the results of MSS.

::: {#tbl-sim1}

{{< include tb1.tex >}}

Bias, Simulated Standard error, and Mean Squared Error 
:::

As described in section @sec-se, GLS standard errors may not be appropriate if heteroskedasticity in the model is misspecified. This could happen if the heteroskedasticity is not linear in parameters or if there are correlations within groups. To show the performance of the GLS standard errors, we consider two additional simulations. To see the impact of heteroskedasticity misspecification, we assume the DGP is given by

$$y_i = \alpha_{1i} + \alpha_{2i} + x_i + (1+x_i + \sqrt{x_i} +\alpha_{1i} + \alpha_{2i} ) \varepsilon_i
$$

To show the impact of ignoring correlation within groups, we consider the case where the error $\varepsilon$ is correlated within groups defined by the first fixed effect. Specifically:

$$\varepsilon_i =0.5*(\sqrt{0.5} z_i + \sqrt{0.5} w_g)$$

where $z_i~N(0,1)$ and $w_g~N(0,1)$, with $g$ being the $g_{th}$ group defined by the first fixed effect.

For the simulation, we run the excercise 5000 times, using a sample of size $N=2000$. The results from both simulations are reported in the @tbl-sim2. We report the average coefficient, simulation-based standard errors, and the standard errors using GLS, robust and clustered estimations.

|             | Het:q25 | Het:q75 | Clust:q25 | Clust:q75 |
|-------------|:-------:|:-------:|:---------:|:---------:|
| Coefficient |  0.550  |  1.442  |   0.775   |   1.229   |
| SIM_SE      |  0.154  |  0.155  |   0.109   |   0.107   |
| GLS_SE      |  0.476  |  0.451  |   0.288   |   0.221   |
| Robust      |  0.140  |  0.139  |   0.087   |   0.088   |
| Cluster     |         |         |   0.097   |   0.097   |

: Heteroskedasticity misspecification and clustered errors {#tbl-sim2}

One of the conclusions from the results in @tbl-sim2 is that the results for the 25th and 75th quantiles are mostly identical, because of the symmetric error we used in the simulation. On the one hand, because the error structure is misspecified, we should expect to see a large bias in the estimated coefficients, especially in cases of misspecified heteroskedasticity. However, the purpose of this exercise is not to demonstrate the unbiasedness of the coefficients, but rather to assess the performance of the standard error estimation.

As expected, the GLS standard errors are biased and the bias is larger in the case of misspecified heteroskedasticity. In fact, with heteroskedasticity misspecification, the average GLS-SE (0.476) is almost three times as large as the simulation-based standard error (0.154). In this first case, robust standard errors perform better, but with a small difference (0.14 to 0.154). In the case of clustered correlation, GLS-SE also performs poorly. Robust standard errors perform better, but seem to underestimate the magnitude of the true standard errors. Finally, cluster standard errors perform the best, with a small difference between the simulation-based standard errors (0.097 to 0.109).

# Illustrative application

In this section we replicate one of the exercises from MSS, allowing for time and individual fixed effects as well as for different standard errors estimations. We use data from @persson_economic_2005, to estimate the relationship between surplus of government as share of GDP, and a measure of quality of democracy (POLITY); log of real income per capita (LYP); trade volume as share of GDP (TRADE); share of population between 15 and 65 years of age (P1564); the share of the population 65 years and older (P65); one-year lag of the dependent variable (LSP); oil prices in US dollars, differntiating between importer and exporter countries (OILIM and OILEX); and the output gap (YGAP). In addition to country fixed effects (as illustrated in MSS), we show results allowing for time fixed effects. @tbl-tb1 and @tbl-tb2 provide the results for the model with and without time fixed effects, respectively. The tables showcase the location and scale coefficients, as well as the quantile coefficients for the 25th, 50th and 75th quantiles. We also report GLS standard errors, robust standard errors (brackets) and clustered standard errors at the country level.

|          | polityt |  lyp   | trade | p1564 |  p65   |  lspl  | oil_im | oil_ex |  ygap  |
|----------|:-------:|:------:|:-----:|:-----:|:------:|:------:|:------:|:------:|:------:|
| Location |         |        |       |       |        |        |        |        |        |
|  coeff   |  0.116  | -0.715 | 0.030 | 0.121 | 0.028  | 0.691  | -0.047 | -0.006 | 0.010  |
|  se_gls  |  0.046  | 0.540  | 0.008 | 0.033 | 0.070  | 0.035  | 0.008  | 0.022  | 0.028  |
|  se_r    |  0.047  | 0.597  | 0.008 | 0.031 | 0.070  | 0.037  | 0.007  | 0.017  | 0.021  |
|  se_cl   |  0.046  | 0.465  | 0.007 | 0.032 | 0.071  | 0.035  | 0.010  | 0.020  | 0.023  |
| Scale    |         |        |       |       |        |        |        |        |        |
|  coeff   | -0.097  | -0.616 | 0.003 | 0.036 | 0.087  | -0.085 | 0.013  | 0.016  | -0.004 |
|  se_gls  |  0.032  | 0.371  | 0.005 | 0.023 | 0.048  | 0.024  | 0.006  | 0.015  | 0.019  |
|  se_r    |  0.031  | 0.398  | 0.005 | 0.020 | 0.049  | 0.025  | 0.005  | 0.010  | 0.015  |
|  se_cl   |  0.048  | 0.800  | 0.008 | 0.031 | 0.067  | 0.029  | 0.004  | 0.010  | 0.012  |
| Q25      |         |        |       |       |        |        |        |        |        |
|  coeff   |  0.191  | -0.239 | 0.028 | 0.093 | -0.039 | 0.756  | -0.057 | -0.018 | 0.013  |
|  se_gls  |  0.059  | 0.684  | 0.010 | 0.042 | 0.088  | 0.045  | 0.010  | 0.027  | 0.035  |
|  se_r    |  0.056  | 0.656  | 0.008 | 0.036 | 0.086  | 0.040  | 0.010  | 0.020  | 0.025  |
|  se_cl   |  0.073  | 0.687  | 0.006 | 0.041 | 0.098  | 0.023  | 0.010  | 0.021  | 0.029  |
| Q50      |         |        |       |       |        |        |        |        |        |
|  coeff   |  0.108  | -0.765 | 0.030 | 0.124 | 0.035  | 0.684  | -0.046 | -0.005 | 0.009  |
|  se_gls  |  0.046  | 0.535  | 0.007 | 0.033 | 0.069  | 0.035  | 0.008  | 0.022  | 0.027  |
|  se_r    |  0.046  | 0.593  | 0.008 | 0.031 | 0.069  | 0.036  | 0.007  | 0.017  | 0.021  |
|  se_cl   |  0.043  | 0.484  | 0.008 | 0.032 | 0.070  | 0.036  | 0.010  | 0.020  | 0.023  |
| Q75      |         |        |       |       |        |        |        |        |        |
|  coeff   |  0.031  | -1.258 | 0.033 | 0.153 | 0.104  | 0.616  | -0.036 | 0.008  | 0.006  |
|  se_gls  |  0.048  | 0.551  | 0.008 | 0.034 | 0.071  | 0.036  | 0.008  | 0.022  | 0.028  |
|  se_r    |  0.049  | 0.696  | 0.009 | 0.034 | 0.075  | 0.043  | 0.007  | 0.018  | 0.023  |
|  se_cl   |  0.039  | 0.919  | 0.012 | 0.041 | 0.079  | 0.055  | 0.010  | 0.022  | 0.020  |

: Determinants of Government Surpluses: Individual Fixed Effects {#tbl-tb1}

As expected, @tbl-tb1 shows that the point estimates are identical to those reported in @mss2019 (Table 6), including analytical standard errors (GLS). With our estimator, however, we are also able to produce both robust and clustered standard errors for location and scale coefficients. Except for a few cases, the robust and clustered standard errors are larger than the GLS standard errors, which may be an indication of misspecification of the model. The GLS standard errors we report differ from those in MSS, because they use panel standard errors, which are equivalent to our clustered standard errors, instead of the analytical standard errors we derive.

Considering the estimated effects across quantiles, we observe few differences in the reported GLS standard errors compared to the analytical standard errors reported in MSS. Our clustered standard errors, however, are closer to the bootstrap-based standard errors the authors report.[^10]

[^10]: The differences in the GLS standard errors may be due that in our derivation the influence function of the standardized $\tau_{th}$ quantile (see #eq-infs) does not have the same leading term as the one reported in MSS (see Theorem 3, and the definition of $W$).

In @tbl-tb2, we report the results including both individual and year fixed effects. Because oil prices only vary across years, the variable is excluded from the model specification. Accounting for time fixed effects does not change the general conclusions that can be drawn, based on the results from @tbl-tb1. The two largest differences are that the log of income per capita has a positive effect on government surpluses, but only for the 25th quantile, because at this point the largest impact on the Scale component is felt. Similarly, we observe that the income gap has an impact on government surplus that is always negative and increasing across quantiles. In both instances, the effects are not statistically significant.

|          | polity |  lyp   | trade | prop1564 | prop65 |  lspl  |  ygap  |
|----------|:------:|:------:|:-----:|:--------:|:------:|:------:|:------:|
| Location |        |        |       |          |        |        |        |
|  coeff   | 0.126  | -0.418 | 0.028 |  0.108   | 0.042  | 0.693  | -0.014 |
|  se_gls  | 0.087  | 1.157  | 0.015 |  0.072   | 0.136  | 0.066  | 0.053  |
|  se_r    | 0.047  | 0.703  | 0.008 |  0.038   | 0.068  | 0.038  | 0.022  |
|  se_cl   | 0.048  | 0.506  | 0.008 |  0.044   | 0.077  | 0.037  | 0.022  |
| Scale    |        |        |       |          |        |        |        |
|  coeff   | -0.095 | -1.255 | 0.005 |  0.033   | 0.040  | -0.081 | 0.008  |
|  se_gls  | 0.081  | 1.073  | 0.014 |  0.067   | 0.126  | 0.061  | 0.049  |
|  se_r    | 0.031  | 0.452  | 0.005 |  0.025   | 0.045  | 0.025  | 0.017  |
|  se_cl   | 0.041  | 0.848  | 0.006 |  0.030   | 0.048  | 0.033  | 0.013  |
| Q25      |        |        |       |          |        |        |        |
|  coeff   | 0.201  | 0.576  | 0.025 |  0.082   | 0.010  | 0.757  | -0.020 |
|  se_gls  | 0.154  | 2.070  | 0.024 |  0.118   | 0.219  | 0.121  | 0.085  |
|  se_r    | 0.058  | 0.751  | 0.008 |  0.049   | 0.080  | 0.040  | 0.026  |
|  se_cl   | 0.073  | 0.761  | 0.006 |  0.052   | 0.087  | 0.023  | 0.027  |
| Q50      |        |        |       |          |        |        |        |
|  coeff   | 0.119  | -0.512 | 0.029 |  0.111   | 0.045  | 0.687  | -0.013 |
|  se_gls  | 0.091  | 1.230  | 0.014 |  0.070   | 0.130  | 0.072  | 0.051  |
|  se_r    | 0.046  | 0.695  | 0.008 |  0.037   | 0.068  | 0.038  | 0.022  |
|  se_cl   | 0.045  | 0.529  | 0.008 |  0.044   | 0.077  | 0.039  | 0.021  |
| Q75      |        |        |       |          |        |        |        |
|  coeff   | 0.041  | -1.555 | 0.033 |  0.138   | 0.078  | 0.619  | -0.007 |
|  se_gls  | 0.067  | 0.898  | 0.011 |  0.053   | 0.098  | 0.052  | 0.038  |
|  se_r    | 0.048  | 0.827  | 0.009 |  0.037   | 0.075  | 0.046  | 0.026  |
|  se_cl   | 0.038  | 0.980  | 0.012 |  0.050   | 0.086  | 0.063  | 0.020  |

: The Determinants of Government Surpluses: Individual and Time Fixed Effects {#tbl-tb2}

# Conclusions

In this paper, we have extended the methodology proposed by @mss2019 in order to estimate quantile regression models with multiple sets of fixed effects as well as with alternative standard errrors. This methodology will allow researchers to implement more-comprehensive analyses of data sets characterized by complex hierarchies and unobserved heterogeneity. This extension is particularly valuable in contexts where group specific effects vary across the conditional distribution of the outcome of interest.

Using a small simulation study, we show that our extended approach is as effective in identifying the parameters of interest as that of @mss2019, even in contexts with two sets of fixed effects. Notably, the bias-corrected estimator based on the split-panel jackknife estimator exhibits promising results, mitigating biases when samples are small but increasing standard errors.

Furthermore, we have assessed the impact of misspecified heteroskedasticity and intracluster correlation on the performance of standard error estimations. Our findings emphasize the importance of using appropriate standard error estimators to ensure accurate inference. In particular, we find that GLS standard errors are biased when the model heteroskedasticity is misspecified and that robust and clustered standard errors perform better in these cases. This may also suggest a venue for future research, in which the validity of the location-scale model assumption is tested.

# References {.unnumbered}

::: {#refs}
:::

{{< pagebreak >}}

\appendix

# Derivation of the influence functions

## Model Identification

The estimation of quantile regression via moments assumes that the DGP is linear in parameters, with an heteroskedastic error term that is also a linear function of parameters:

$$\begin{aligned}
y_i = x_i'\beta + \nu_i \\
\nu_i = \varepsilon_i \times x_i'\gamma
\end{aligned}
$$

where $\varepsilon$ is an unobserved i.i.d. random variable that is independent of $x$ and such that $x\gamma$ is larger than 0 for any $x$.

In this case, the $\tau_{th}$ conditional quantile model can be written as
 
$$Q_y(\tau|X) = x'(\beta +Q_\varepsilon(\tau)  \times \gamma)$$

This model is identified under the following conditions:

$$\begin{aligned}
  E[(y_i-x_i'\beta)x_i ]  &= E[h_{1,i}]=0 \\
  E[ (|y_i-x_i'\beta|-x_i' \gamma) x_i ] &=E[h_{2,i}]=0 \\
  E\left[  \mathbb{1}\left( Q_\varepsilon(\tau) x_i'\gamma +x_i'\beta\geq  y_i  \right) - \tau \right] 
   &=E[h_{3,i}]=0 
\end{aligned}
$$

For simplicity, the rest of the appendix uses $q_\tau$ to represent  $Q_\varepsilon(\tau)$. 

## Estimation of the Variance-Covariance Matrix

In this model, to estimate the variance-covariance matrix the set of coefficients $\theta'=[\beta' \ \gamma' \ q_\tau]$, we need to obtain the influence functions of all coefficients, which are defined as

$$\lambda_i = \bar G(\theta)^{-1}
\begin{bmatrix}
h_{1,i} \\
h_{2,i} \\
h_{3,i}
\end{bmatrix}
$$

where the Jacobian matrix $\bar G(\theta)$ is defined as

$$\bar G(\theta) = \begin{bmatrix}
\bar G_{11} & \bar G_{12} & \bar G_{13} \\
\bar G_{21} & \bar G_{22} & \bar G_{23} \\
\bar G_{31} & \bar G_{32} & \bar G_{13} \\
\end{bmatrix}
$$

with

$$\bar G_{j,k} = - \frac 1 N \sum_{i=1}^N \frac{\partial h_{j,i}}{\partial \theta_k'} \ \forall j,k \in 1,2,3
$$

First Moment Condition: Location Model

$$h_{1,i}=x_i(y_i-x_i'\beta)$$

$$\begin{aligned}
\bar G_{1,1} &=- \frac{1}{N} \sum_{i=1}^N \frac{\partial h_{1,i}}{\partial \beta'} \\
             &=- \frac{1}{N} \sum_{i=1}^N (-x_i x_i') \\
             &= N^{-1} X'X
\end{aligned}
$$

$$
\bar G_{1,2} = \bar G_{1,3} = 0
$$

Second Moment Condition: Scale model

$$h_{2,i}=x_i(|y_i-x_i'\beta|-x_i'\gamma)$$

$$\begin{aligned}
\bar G_{2,1} &= -\frac{1}{N} \sum \frac{\partial h_{2,i}}{\partial \beta'} \\
             &=  \frac{1}{N} \sum x_i x_i' \frac{y_i-x_i'\beta}{|y_i-x_i'\beta|} \\
\frac{y_i-x_i'\beta}{|y_i-x_i'\beta|} &= sign(y_i-x_i'\beta) \\            
\end{aligned}
$$

Under the assumption $\varepsilon_i \times x\gamma$, or in this case $y_i-x_i'\beta$, is uncorrelated with $x$, we can simplify the expression as

$$\begin{aligned}
\bar G_{2,1} &= N^{-1} \left(N^{-1}\sum sign(y_i-x_i'\beta)\right) \sum x_i x_i' \\
&= N^{-1} E[sign(y_i-x_i'\beta)] X'X
\end{aligned}
$$

$$\begin{aligned}
\bar G_{2,2} &= -\frac{1}{N} \sum \frac{\partial h_{2,i}}{\partial \gamma'} \\
             &=  \frac{1}{N} \sum x_i x_i' \\
             &= N^{-1} X'X
\end{aligned}
$$

$$\bar G_{2,3}=0$$

Third Moment Condition: Quantile of Standardized Residual

$$\begin{aligned}
h_{3,i} &= \mathbb{1}\left( q_\tau  x_i'\gamma +x_i'\beta - y_i \geq 0 \right) - \tau \text{ or}\\
h_{3,i} &= \mathbb{1}\left( q_\tau  \geq \frac{y_i- x_i'\beta}{x_i'\gamma}  \right) - \tau = \mathbb{1}\big( q_\tau \geq \varepsilon  \big) - \tau \\
\end{aligned}
$$

Because the indicator function $\mathbb{1}()$ is not differentiable, we borrow from the nonparametric literature to approximate this function with a kernel function. Call $k()$ a well behaved kernel function that is symetric around 0, and $K()$ its integral, with range between 0 and 1. With an arbirarily small bandwidth $h$, we can use the function $K()$ to approximate the indicator function:

$$
\lim_{h\rightarrow 0} K\left(\frac{z}{h}\right) \approx \mathbb{1}(z\geq 0)
$$

Thus the function $h_{3,i}$ can be approximated as

$$h_{3,i} \approx K\left( \frac{1}{h} \Big( q_\tau x_i'\gamma +x_i'\beta - y_i  \Big) \right) - \tau
$$

Now, we can obtain the Jacobian matrix $\bar G_{3,1}$ as:

$$\begin{aligned}
\bar G_{3,1} &= -\frac{1}{N} \sum \frac{\partial h_{3,i}}{\partial \beta'} \\
             &= -N^{-1} \sum \frac{1}{h} k\left( \frac{1}{h} \Big( q_\tau x_i'\gamma +x_i'\beta - y_i  \Big) \right) x_i' \\ 
             &= -N^{-1} \sum \frac{1}{h} k\left( \frac{1}{h} \big( q_\tau x_i'\gamma - \nu_i \big)   \right) x_i'  \\
             &= -N^{-1} \sum \frac{1}{h} k\left( \frac{1}{h} ( q_\tau - \varepsilon_i ) x_i'\gamma  \right) x_i'  
\end{aligned}
$$

If we condition on $X$, use the law of iterated expectations, and assume that $\varepsilon_i$ is homoskedastic, we can obtain:

$$\begin{aligned}
\bar G_{3,1} &= -N^{-1} \sum \frac{1}{h} k\left( \frac{1}{h} ( q_\tau - \varepsilon_i ) x_i'\gamma  \right) x_i'  \\
             &= -N^{-1} \sum \frac{1}{h} k\left( \frac{q_\tau - \varepsilon_i}{h}  \right)  \frac{x_i'}{x_i'\gamma}  \\
             &= -N^{-1} f_\varepsilon (q_\tau) \sum  \frac{x_i'}{x_i'\gamma}  
\end{aligned}
$$

Finally, this simplifies to:
$$\begin{aligned}
\bar G_{3,1} &\simeq -  f_\varepsilon (q_\tau) \frac{\bar x_i'}{ \bar x_i' \gamma} 
\end{aligned}
$$

where we use the fact that asymptotically, the expression $\frac{1}{N}\sum \frac{a_i}{b_i}$ can be approximated using Taylor expansions by $\frac{\bar a}{\bar b}$. [^11] Thus, we can rewrite the last term as

[^11]: This approximation will be useful when we consider the estimation of the influence functions.

The Jacobian for the second matrix $\bar G_{3,2}$ can be derived similarly:

$$\begin{aligned}
\bar G_{3,2} &= -\frac{1}{N} \sum \frac{\partial h_{3,i}}{\partial \gamma'} \\
             &= -N^{-1} \sum \frac{1}{h} k\left( \frac{1}{h} ( q_\tau - \varepsilon_i ) x_i'\gamma  \right) q_\tau x_i'  \\
             &= -N^{-1} \sum \frac{1}{h} k\left( \frac{q_\tau - \varepsilon_i}{h}    \right) q_\tau \frac{x_i'}{x_i'\gamma}  \\
             &\simeq  -  f(q_\tau)  q_\tau \frac{\bar x'}{\bar x'\gamma}
\end{aligned}
$$

and the Jacobian for the third matrix $\bar G_{3,3}$ is

$$\begin{aligned}
\bar G_{3,3} &= -\frac{1}{N} \sum \frac{\partial h_{3,i}}{\partial q_\tau} \\
             &= -N^{-1} \sum \frac{1}{h} k\left( \frac{1}{h} ( q_\tau - \varepsilon_i ) x_i'\gamma  \right) x_i'\gamma  \\
             &= -N^{-1} \sum \frac{1}{h} k\left( \frac{q_\tau - \varepsilon_i}{h}   \right) \frac{x_i'\gamma}{x_i'\gamma}  \\
             &\simeq  -  f(q_\tau)  
\end{aligned}
$$

## Influence Functions

Location Coefficients

$$\lambda_i(\beta) = \bar G^{-1}_{1,1} h_{1,i} = N (X'X)^{-1}(x_i (y_i-x_i'\beta)) = N (X'X)^{-1}(x_i \nu_i)
$$

which can also be written as a function of the standardized residuals:

$$\lambda_i(\beta) = \bar G^{-1}_{1,1} h_{1,i} = N (X'X)^{-1}(x_i (y_i-x_i'\beta)) = N (X'X)^{-1}(x_i ( x_i'\gamma \times \varepsilon))
$$

Scale Coefficients

$$\begin{aligned}
\lambda_i(\gamma)&=\bar G_{2,2}^{-1}\Big(h_{2,i}-\bar G_{2,1} \lambda_i(\beta)\Big) \\
&=N (X'X)^{-1} \Big(x_i(|\nu_i|-x_i' \gamma) 
- N^{-1} E[sign(\nu_i)] X'X \big[ N (X'X)^{-1}(x_i \nu_i) \big] \Big) \\
&=N (X'X)^{-1} \Big(x_i(|\nu_i|-x_i' \gamma) - E[sign(\nu_i)] (x_i \nu_i)  \Big) \\
&=N (X'X)^{-1} x_i \Big( |\nu_i| - E[sign(\nu_i)] \nu_i -x_i' \gamma \Big) 
\end{aligned}
$$

However,

$$\begin{aligned}
|\nu_i| &= \nu_i \times \mathbb{1}(\nu_i \geq 0) - \nu_i \times \mathbb{1}(\nu_i < 0) \\
|\nu_i| &= \nu_i \times \mathbb{1}(\nu_i \geq 0) - \nu_i \times [1-\mathbb{1}(\nu_i \geq 0)] \\
|\nu_i| &= 2 \nu_i \times \mathbb{1}(\nu_i \geq 0) - \nu_i  
\end{aligned}
$$

and

$$\begin{aligned}
E[sign(\nu_i)] &= E[\mathbb{1}(\nu_i \geq 0)] - E[\mathbb{1}(\nu_i < 0)] \\
E[sign(\nu_i)] &= E[\mathbb{1}(\nu_i \geq 0)] - E[(1-\mathbb{1}(\nu_i \geq 0))] \\
E[sign(\nu_i)] &= 2 E[\mathbb{1}(\nu_i \geq 0)] - 1
\end{aligned}
$$

Thus,

$$\begin{aligned}
\lambda_i(\gamma) &= N(X'X)^{-1} x_i   \Big( 2 \nu_i \times \mathbb{1}(\nu_i \geq 0) - \nu_i  - ( 2 E[\mathbb{1}(\nu_i \geq 0)] - 1) \nu_i -x_i' \gamma \Big) \\
  &= N(X'X)^{-1} x_i   \Big( 2 \nu_i \times \mathbb{1}(\nu_i \geq 0) -  2 E[\mathbb{1}(\nu_i \geq 0)] \nu_i -x_i' \gamma \Big) \\
  &= N(X'X)^{-1} x_i   \Big( 2 \nu_i \times \big[ \mathbb{1}(\nu_i \geq 0) -  E[\mathbb{1}(\nu_i \geq 0)] \big] -x_i'\gamma \Big) \\
  &= N(X'X)^{-1} x_i   \Big( \tilde \nu_i -x_i' 
  \gamma \Big)
\end{aligned}
$$

This last expression is the equivalent simplification used in @mss2019 and @im2000. If the scale function is strictly positive, it also follows that $\mathbb{1}(\nu_i \geq 0)= \mathbb{1}(\varepsilon_i \geq 0)$. Thus, it can be simplified as

$$\begin{aligned}
\lambda_i(\gamma) &= N(X'X)^{-1} x_i ( x_i' \gamma ) \times (\tilde \varepsilon_i -1\big)
\end{aligned}
$$

Quantile of Standardized Residual

$$\begin{aligned}
\lambda_i(q_\tau)&=\bar G_{3,3}^{-1}
\Big(
 h_{3,i}-\bar G_{3,1} \lambda_i(\beta)-\bar G_{3,2} \lambda_i(\gamma)
\Big) \\
&=-\frac{1}{f_{\varepsilon}(q_\tau)} \times \Bigg( \Big(\mathbb{1} ( q_\tau  \geq \varepsilon  ) - \tau \Big)  \\
&+ f_{\varepsilon} (q_\tau) \frac{\bar x_i'}{\bar x_i'\gamma} 
N (X'X)^{-1} x_i  ( x_i'\gamma \times \varepsilon) \\
&+ f_{\varepsilon}(q_\tau) q_\tau \frac{\bar x_i'}{\bar x_i'\gamma} N(X'X)^{-1} x_i   \big( \tilde \nu_i -x_i' 
  \gamma \big) 
\Bigg) \\
&=\frac{\tau-\mathbb{1}\big( q_\tau  \geq \varepsilon  \big) }{f_{\varepsilon}(q_\tau)}
- \frac{ x_i'\gamma \times \varepsilon_i }{\bar x_i'\gamma} 
-  q_\tau \frac{ \tilde \nu_i -x_i' 
  \gamma }{\bar x_i'\gamma} 
\end{aligned}
$$

# Implementation

The method described here can be implemented using any of the following packages:

-   `mmqreg` in Stata: \`net install mmqreg, from(https://friosavila.github.io/stpackages)
-   `mmqreg` in R: Program available in mmqreg repository on GitHub (https://github.com/friosavila/mmqreg)
-   `mmqreg` in Python:
-   `mmqreg` in Julia:
